#!/bin/bash
bindir=../../gbin
$bindir/lsieve 1000000 1070000 2> /dev/null
##$bindir/lsieve 2> /dev/null
$bindir/postProcessing.pl -r tst250.relations -ro rels1 -c REMOVE_DUPLICATES
$bindir/postProcessing.pl -r rels1 -ro rels2 -f 10000 -e 5000 -c REMOVE_SINGLETONS
$bindir/postProcessing.pl -r rels2 -ro rels3a -f 1000 -e 500 -c PRUNE
$bindir/postProcessing.pl -r rels3a -ro rels3b -f 1000 -e 500 -c PRUNE
$bindir/postProcessing.pl -r rels3b -ro rels4b -rsp -ml 10 -mp 20 -c MERGE -f 1000 -e 500
$bindir/postProcessing.pl -rsi rels4b.sets -rspi -rs rels4c.sets -rsp -merge_only -ml 18 -mm 10 -mp 30 -c MERGE -f 1000 -e 500
$bindir/postProcessing.pl -rsi rels4c.sets -rspi -rs rels4d.sets -rsp -merge_only -ml 30 -mm 18 -mp 30 -c MERGE -f 1000 -e 500
$bindir/postProcessing.pl -f 1000 -r rels4b -rsi rels4d.sets -rspi rels4d.sets.primes -m mat4d -c BUILD_MATRIX
$bindir/postProcessing.pl -m mat4d -d dep4d -c SOLVE_MATRIX
$bindir/postProcessing.pl -r rels4b -rsi rels4d.sets -d dep4d -c PROCESS_DEPENDENCIES
